/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICrossChainProofOfHumanity,
  ICrossChainProofOfHumanityInterface,
} from "../../interfaces/ICrossChainProofOfHumanity";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes20",
        name: "humanityID",
        type: "bytes20",
      },
    ],
    name: "boundTo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_human",
        type: "address",
      },
    ],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICrossChainProofOfHumanity__factory {
  static readonly abi = _abi;
  static createInterface(): ICrossChainProofOfHumanityInterface {
    return new Interface(_abi) as ICrossChainProofOfHumanityInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICrossChainProofOfHumanity {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICrossChainProofOfHumanity;
  }
}
