/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICrossChainProofOfHumanity__factory } from "./ICrossChainProofOfHumanity__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IRewardDistributor__factory } from "./IRewardDistributor__factory";
