/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReferralPayoutDistributor,
  IReferralPayoutDistributorInterface,
} from "../../interfaces/IReferralPayoutDistributor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "recipients",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "distribute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOperator",
        type: "address",
      },
    ],
    name: "setOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newToken",
        type: "address",
      },
    ],
    name: "setToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReferralPayoutDistributor__factory {
  static readonly abi = _abi;
  static createInterface(): IReferralPayoutDistributorInterface {
    return new Interface(_abi) as IReferralPayoutDistributorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReferralPayoutDistributor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IReferralPayoutDistributor;
  }
}
