/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardDistributorV2,
  IRewardDistributorV2Interface,
} from "../../interfaces/IRewardDistributorV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes20",
        name: "referrerHumanityId",
        type: "bytes20",
      },
      {
        internalType: "bytes20",
        name: "refereeHumanityId",
        type: "bytes20",
      },
      {
        internalType: "uint8",
        name: "role",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "expireAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newCrossChainProofOfHumanity",
        type: "address",
      },
    ],
    name: "setCrossChainProofOfHumanity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newMaxAmount",
        type: "uint256",
      },
    ],
    name: "setMaxAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newToken",
        type: "address",
      },
    ],
    name: "setToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newSigner",
        type: "address",
      },
    ],
    name: "setVoucherSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRewardDistributorV2__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardDistributorV2Interface {
    return new Interface(_abi) as IRewardDistributorV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRewardDistributorV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRewardDistributorV2;
  }
}
