/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockCrossChainProofOfHumanity__factory } from "./MockCrossChainProofOfHumanity__factory";
export { MockERC20__factory } from "./MockERC20__factory";
