/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockCrossChainProofOfHumanity } from "./MockCrossChainProofOfHumanity";
export type { MockERC20 } from "./MockERC20";
