/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockCrossChainProofOfHumanityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "boundTo"
      | "isHuman"
      | "setBoundTo"
      | "setIsHuman"
      | "setupHuman"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "boundTo", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isHuman",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBoundTo",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIsHuman",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setupHuman",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "boundTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isHuman", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBoundTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setIsHuman", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setupHuman", data: BytesLike): Result;
}

export interface MockCrossChainProofOfHumanity extends BaseContract {
  connect(runner?: ContractRunner | null): MockCrossChainProofOfHumanity;
  waitForDeployment(): Promise<this>;

  interface: MockCrossChainProofOfHumanityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  boundTo: TypedContractMethod<[humanityID: BytesLike], [string], "view">;

  isHuman: TypedContractMethod<[_human: AddressLike], [boolean], "view">;

  setBoundTo: TypedContractMethod<
    [humanityID: BytesLike, _address: AddressLike],
    [void],
    "nonpayable"
  >;

  setIsHuman: TypedContractMethod<
    [_human: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setupHuman: TypedContractMethod<
    [humanityID: BytesLike, _address: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "boundTo"
  ): TypedContractMethod<[humanityID: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isHuman"
  ): TypedContractMethod<[_human: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setBoundTo"
  ): TypedContractMethod<
    [humanityID: BytesLike, _address: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIsHuman"
  ): TypedContractMethod<
    [_human: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setupHuman"
  ): TypedContractMethod<
    [humanityID: BytesLike, _address: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
