/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICrossChainProofOfHumanity } from "./ICrossChainProofOfHumanity";
export type { IERC20 } from "./IERC20";
export type { IRewardDistributor } from "./IRewardDistributor";
