/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RewardDistributorV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "claimed"
      | "crossChainProofOfHumanity"
      | "maxAmount"
      | "owner"
      | "setCrossChainProofOfHumanity"
      | "setMaxAmount"
      | "setToken"
      | "setVoucherSigner"
      | "token"
      | "transferOwnership"
      | "voucherSigner"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "CrossChainProofOfHumanityChanged"
      | "MaxAmountChanged"
      | "OwnershipTransferred"
      | "TokenChanged"
      | "VoucherSignerChanged"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crossChainProofOfHumanity",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxAmount", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setCrossChainProofOfHumanity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVoucherSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voucherSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "crossChainProofOfHumanity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxAmount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCrossChainProofOfHumanity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVoucherSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voucherSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    referrerHumanityId: BytesLike,
    refereeHumanityId: BytesLike,
    role: BigNumberish,
    beneficiary: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    referrerHumanityId: string,
    refereeHumanityId: string,
    role: bigint,
    beneficiary: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    referrerHumanityId: string;
    refereeHumanityId: string;
    role: bigint;
    beneficiary: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainProofOfHumanityChangedEvent {
  export type InputTuple = [
    oldCrossChainProofOfHumanity: AddressLike,
    newCrossChainProofOfHumanity: AddressLike
  ];
  export type OutputTuple = [
    oldCrossChainProofOfHumanity: string,
    newCrossChainProofOfHumanity: string
  ];
  export interface OutputObject {
    oldCrossChainProofOfHumanity: string;
    newCrossChainProofOfHumanity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxAmountChangedEvent {
  export type InputTuple = [
    oldMaxAmount: BigNumberish,
    newMaxAmount: BigNumberish
  ];
  export type OutputTuple = [oldMaxAmount: bigint, newMaxAmount: bigint];
  export interface OutputObject {
    oldMaxAmount: bigint;
    newMaxAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenChangedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoucherSignerChangedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardDistributorV2 extends BaseContract {
  connect(runner?: ContractRunner | null): RewardDistributorV2;
  waitForDeployment(): Promise<this>;

  interface: RewardDistributorV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<
    [
      referrerHumanityId: BytesLike,
      refereeHumanityId: BytesLike,
      role: BigNumberish,
      expireAt: BigNumberish,
      amount: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  crossChainProofOfHumanity: TypedContractMethod<[], [string], "view">;

  maxAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setCrossChainProofOfHumanity: TypedContractMethod<
    [_newCrossChainProofOfHumanity: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxAmount: TypedContractMethod<
    [_newMaxAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setToken: TypedContractMethod<[_newToken: AddressLike], [void], "nonpayable">;

  setVoucherSigner: TypedContractMethod<
    [_newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  voucherSigner: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      referrerHumanityId: BytesLike,
      refereeHumanityId: BytesLike,
      role: BigNumberish,
      expireAt: BigNumberish,
      amount: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "crossChainProofOfHumanity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setCrossChainProofOfHumanity"
  ): TypedContractMethod<
    [_newCrossChainProofOfHumanity: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxAmount"
  ): TypedContractMethod<[_newMaxAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setToken"
  ): TypedContractMethod<[_newToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVoucherSigner"
  ): TypedContractMethod<[_newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voucherSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainProofOfHumanityChanged"
  ): TypedContractEvent<
    CrossChainProofOfHumanityChangedEvent.InputTuple,
    CrossChainProofOfHumanityChangedEvent.OutputTuple,
    CrossChainProofOfHumanityChangedEvent.OutputObject
  >;
  getEvent(
    key: "MaxAmountChanged"
  ): TypedContractEvent<
    MaxAmountChangedEvent.InputTuple,
    MaxAmountChangedEvent.OutputTuple,
    MaxAmountChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenChanged"
  ): TypedContractEvent<
    TokenChangedEvent.InputTuple,
    TokenChangedEvent.OutputTuple,
    TokenChangedEvent.OutputObject
  >;
  getEvent(
    key: "VoucherSignerChanged"
  ): TypedContractEvent<
    VoucherSignerChangedEvent.InputTuple,
    VoucherSignerChangedEvent.OutputTuple,
    VoucherSignerChangedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Claimed(bytes20,bytes20,uint8,address,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "CrossChainProofOfHumanityChanged(address,address)": TypedContractEvent<
      CrossChainProofOfHumanityChangedEvent.InputTuple,
      CrossChainProofOfHumanityChangedEvent.OutputTuple,
      CrossChainProofOfHumanityChangedEvent.OutputObject
    >;
    CrossChainProofOfHumanityChanged: TypedContractEvent<
      CrossChainProofOfHumanityChangedEvent.InputTuple,
      CrossChainProofOfHumanityChangedEvent.OutputTuple,
      CrossChainProofOfHumanityChangedEvent.OutputObject
    >;

    "MaxAmountChanged(uint256,uint256)": TypedContractEvent<
      MaxAmountChangedEvent.InputTuple,
      MaxAmountChangedEvent.OutputTuple,
      MaxAmountChangedEvent.OutputObject
    >;
    MaxAmountChanged: TypedContractEvent<
      MaxAmountChangedEvent.InputTuple,
      MaxAmountChangedEvent.OutputTuple,
      MaxAmountChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenChanged(address,address)": TypedContractEvent<
      TokenChangedEvent.InputTuple,
      TokenChangedEvent.OutputTuple,
      TokenChangedEvent.OutputObject
    >;
    TokenChanged: TypedContractEvent<
      TokenChangedEvent.InputTuple,
      TokenChangedEvent.OutputTuple,
      TokenChangedEvent.OutputObject
    >;

    "VoucherSignerChanged(address,address)": TypedContractEvent<
      VoucherSignerChangedEvent.InputTuple,
      VoucherSignerChangedEvent.OutputTuple,
      VoucherSignerChangedEvent.OutputObject
    >;
    VoucherSignerChanged: TypedContractEvent<
      VoucherSignerChangedEvent.InputTuple,
      VoucherSignerChangedEvent.OutputTuple,
      VoucherSignerChangedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
